Private events: Ruby on Rails project based on associations.
diamond-nicholas/private-events pull request #1
Opened 2021-03-26 21:20 UTC by franklinben23

In this project, we have created an application that allows you to create events as a registered user, attend those events, read the information of those events including the full attendee list, and see all the events you're attending on your user page. Events are divided into upcoming (future events) and past by referencing just the date.

2021-03-27 20:54 UTC, cyonii requested changes
# Status: Changes Required ♻️✍️

Hello @franklinben23 & @diamond-nicholas, you have done great so far.

## To Highlight
- Good PR description

## To Improve
You've done a great job so far, but there are a few issues you need to fix in other to meet this project's specifications. Also, look at the inline comments and fix the issues I pointed out.

- [ ] Improve your future commit messages to be more descriptive, avoid using short phrases that are less informative, e.g, _"Fix error"_ or _"Update route"_
- [ ] User's show page should displays events the user has created, and events that the user is attending, and has attended - to be separated in past and upcoming sections **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
- [ ] 


## Nice to Have (OPTIONAL)


Please note that these are optional suggestions, therefore, you are not obliged to implement them, but I recommend that you do.

- [ ] [OPTIONAL] Your application breaks when I try to log out, it'll be nice to have a functional logout feature.

2021-03-27 20:54 UTC, cyonii commented on app/views/events/index.html.erb
> +    <% @events.future.each do |event| %>
Please remember to keep application logic away from the view,
instead of calling `@event.future` in the view you can save the objects in a variable e.g,
```ruby
@upcoming_events = @events.future
```
Then use `@upcoming_events` in your view

2021-03-27 20:54 UTC, cyonii commented on app/views/events/index.html.erb
> +    <% @events.past.each do |event| %>
No app logic in view, just like `@upcoming_events` save the upcoming events in a variable so that you don't expose your app logic.,
```ruby
@past_events = @event.past
```

Then use `@past_events` in your view

2021-03-30 17:49 UTC, MahmoudBakr23 approved these changes
# **Approved ✔✔**

<hr>

Hello there :)
Great job working on this project and on the requested changes 🎉✔ Congratulations
You may now merge and submit.
Good luck with the next and happy coding 👍👨‍💻💻

2021-04-02 05:46 UTC, merged